# Title of your blog; shows in the header
name: "ramblings"

# Description of your content (will only be used on Google Search)
description: "ramblings"

# Your name. Will show in your footer + sidebar
author: "zeno pelgrims"

url: "https://zpelgrims.github.io"
baseurl:

# A short presentation of yourself. Will show in the sidebar, under your name. Best usage would be between 30 to 50 words.
author-bio: "fill this in yo"

# Social Accounts (mine, as placeholders)

twitter: zenopelgrims
github: zpelgrims

# Google Analytics (you may want to changes these with yours or even delete :)

ga_domain: 
ga_tracking_id: 

# Other (refer to http://jekyllrb.com/docs/home/ for further details on the below)

markdown: kramdown
permalink: pretty
highlighter: rouge

paginate: 10
paginate_path: "/page/:num"

# SCSS

sass:
  sass_dir: _scss
  style: :compressed
